name: stripe_payment
description: A flutter plugin to integrate the stripe plugin for iOS and Android. Currently only adding a credit card as source is implemented.
version: 0.0.3
author: Jonas Bark <jonas.bark@gmx.de>
homepage: https://github.com/jonasbark/flutter_stripe_payment

environment:
    sdk: ">=1.19.0 <2.0.0"
    flutter: "^0.1.2"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: de.jonasbark.stripepayment
    pluginClass: StripePaymentPlugin