name: stripe_payment
description: A Flutter plugin to integrate the stripe libraries for iOS and Android. Supports Apple / Google Pay, SCA, PSD2 and much more.
version: 1.1.0
homepage: https://github.com/jonasbark/flutter_stripe_payment

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.jonasbark.stripepayment
        pluginClass: StripePaymentPlugin
      ios:
        pluginClass: StripePaymentPlugin
